############# English navigation ##############

# main menu


# footer menu
[[footer]]
name = "LevelupHN"
url = "/leveluphn"
weight = 1

[[footer]]
name = "Contact Us"
url = "mailto:asd@example.com"
weight = 2
